[tool.bumpversion]
current_version = "0.9.1"
commit = true
tag = false

[[tool.bumpversion.files]]
filename = "helm/Chart.yaml"
search = 'version: {current_version}'
replace = 'version: {new_version}'

[[tool.bumpversion.files]]
filename = "helm/Chart.yaml"
search = 'appVersion: "{current_version}"'
replace = 'appVersion: "{new_version}"'

[[tool.bumpversion.files]]
filename = "versions.toml"
search = 'chart-version = "{current_version}"'
replace = 'chart-version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "versions.toml"
search = 'app-version = "{current_version}"'
replace = 'app-version = "{new_version}"'
