{{- if and .Values.api.enabled .Values.api.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "ref.fullname" . }}-api
  labels:
    app.kubernetes.io/component: api
    {{- include "ref.labels" . | nindent 4 }}
    {{- with .Values.api.httpRoute.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.api.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.api.httpRoute.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.api.httpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    {{- with .Values.api.httpRoute.filters }}
    filters:
      {{- toYaml . | nindent 4 }}
    {{- end }}
    backendRefs:
    - name: {{ include "ref.fullname" . }}-api
      port: {{ .Values.api.service.port }}
{{- end }}
