{{- if .Values.api.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ref.fullname" . }}-api
  labels:
    app.kubernetes.io/component: api
    {{- include "ref.labels" . | nindent 4 }}
stringData:
  {{- tpl (toYaml .Values.api.env) . | nindent 2}}
{{- end }}
