{{- if and .Values.api.enabled .Values.api.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ref.fullname" . }}-api
  labels:
    app.kubernetes.io/component: api
    {{- include "ref.labels" . | nindent 4 }}
  {{- with .Values.api.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.api.serviceAccount.automount }}
{{- end }}
