api:
  env:
    SECRET_KEY: ci-test-secret
    REF_DATABASE_URL: sqlite:////tmp/ref.db
  volumes:
  - name: tmp
    emptyDir: {}
  volumeMounts:
  - name: tmp
    mountPath: /tmp
    readOnly: false

service:
  type: NodePort

flower:
  podSecurityContext:
    runAsUser: 1000

defaults:
  podSecurityContext:
    runAsUser: 1000
  volumes:
  - name: gha-cached
    hostPath:
      path: /cache/ref-config
  - name: tmp
    emptyDir: {}
  volumeMounts:
  - name: gha-cached
    mountPath: /ref
    readOnly: false
  - name: tmp
    mountPath: /tmp
    readOnly: false

dragonfly:
  extraArgs:
  - --proactor_threads=1
  - --maxmemory=256mb
