apiVersion: v2
name: ref
description: A Helm chart for Kubernetes
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.9.1

# This is the version number of the application being deployed.
# This should match the chart version for coupled versioning.
appVersion: "0.9.1"

dependencies:
- name: dragonfly
  version: v1.33.1
  repository: oci://ghcr.io/dragonflydb/dragonfly/helm
  condition: dragonfly.enabled
