apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ref.fullname" . }}-flower-config
  labels:
    app.kubernetes.io/component: flower
    {{- include "ref.labels" . | nindent 4 }}
data:
  celeryconfig.py: |
    {{- .Values.flower.celeryConfig | nindent 4 }}

    print("Loaded celeryconfig")
