apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ref.fullname" . }}-flower
  labels:
    app.kubernetes.io/component: flower
    {{- include "ref.labels" . | nindent 4 }}
spec:
  {{- if not .Values.flower.autoscaling.enabled }}
  replicas: {{ .Values.flower.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: flower
      {{- include "ref.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/flower/secret.yaml") . | sha256sum }}
      {{- with .Values.flower.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: flower
        {{- include "ref.labels" . | nindent 8 }}
        {{- with .Values.flower.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ref.fullname" . }}-flower
      {{- with .Values.flower.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: flower
        {{- with .Values.flower.securityContext }}
        securityContext:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        image: "{{ .Values.flower.image.repository }}:{{ .Values.flower.image.tag }}"
        imagePullPolicy: {{ .Values.flower.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: {{ include "ref.fullname" . }}-flower
        ports:
        - name: http
          containerPort: {{ .Values.flower.service.port }}
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: http
        {{- with .Values.flower.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.flower.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 12 }}
        {{- end }}
      {{- with .Values.flower.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.flower.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.flower.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.flower.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
