{{- if .Values.flower.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ref.fullname" . }}-flower
  labels:
    app.kubernetes.io/component: flower
    {{- include "ref.labels" . | nindent 4 }}
    {{- with .Values.flower.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.flower.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.flower.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  tls:
  - hosts:
    - {{ .Values.flower.ingress.host | quote }}
    secretName: {{ include "ref.fullname" . }}-flower-ingress-cert
  rules:
  - host: {{ .Values.flower.ingress.host | quote }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "ref.fullname" . }}-flower
            port:
              number: {{ .Values.flower.service.port }}
{{- end }}
